// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/articleService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticleProps struct {
	Prop                 string   `protobuf:"bytes,1,opt,name=prop,proto3" json:"prop,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleProps) Reset()         { *m = ArticleProps{} }
func (m *ArticleProps) String() string { return proto.CompactTextString(m) }
func (*ArticleProps) ProtoMessage()    {}
func (*ArticleProps) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{0}
}

func (m *ArticleProps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleProps.Unmarshal(m, b)
}
func (m *ArticleProps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleProps.Marshal(b, m, deterministic)
}
func (m *ArticleProps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleProps.Merge(m, src)
}
func (m *ArticleProps) XXX_Size() int {
	return xxx_messageInfo_ArticleProps.Size(m)
}
func (m *ArticleProps) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleProps.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleProps proto.InternalMessageInfo

func (m *ArticleProps) GetProp() string {
	if m != nil {
		return m.Prop
	}
	return ""
}

func (m *ArticleProps) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ArticleTag struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleTag) Reset()         { *m = ArticleTag{} }
func (m *ArticleTag) String() string { return proto.CompactTextString(m) }
func (*ArticleTag) ProtoMessage()    {}
func (*ArticleTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{1}
}

func (m *ArticleTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleTag.Unmarshal(m, b)
}
func (m *ArticleTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleTag.Marshal(b, m, deterministic)
}
func (m *ArticleTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleTag.Merge(m, src)
}
func (m *ArticleTag) XXX_Size() int {
	return xxx_messageInfo_ArticleTag.Size(m)
}
func (m *ArticleTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleTag.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleTag proto.InternalMessageInfo

func (m *ArticleTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ArticleComment struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleComment) Reset()         { *m = ArticleComment{} }
func (m *ArticleComment) String() string { return proto.CompactTextString(m) }
func (*ArticleComment) ProtoMessage()    {}
func (*ArticleComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{2}
}

func (m *ArticleComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleComment.Unmarshal(m, b)
}
func (m *ArticleComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleComment.Marshal(b, m, deterministic)
}
func (m *ArticleComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleComment.Merge(m, src)
}
func (m *ArticleComment) XXX_Size() int {
	return xxx_messageInfo_ArticleComment.Size(m)
}
func (m *ArticleComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleComment.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleComment proto.InternalMessageInfo

func (m *ArticleComment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleComment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ArticleComment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleComment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArticleCommentLast struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Blog                 int64    `protobuf:"varint,5,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleCommentLast) Reset()         { *m = ArticleCommentLast{} }
func (m *ArticleCommentLast) String() string { return proto.CompactTextString(m) }
func (*ArticleCommentLast) ProtoMessage()    {}
func (*ArticleCommentLast) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{3}
}

func (m *ArticleCommentLast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleCommentLast.Unmarshal(m, b)
}
func (m *ArticleCommentLast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleCommentLast.Marshal(b, m, deterministic)
}
func (m *ArticleCommentLast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleCommentLast.Merge(m, src)
}
func (m *ArticleCommentLast) XXX_Size() int {
	return xxx_messageInfo_ArticleCommentLast.Size(m)
}
func (m *ArticleCommentLast) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleCommentLast.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleCommentLast proto.InternalMessageInfo

func (m *ArticleCommentLast) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleCommentLast) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ArticleCommentLast) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleCommentLast) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArticleCommentLast) GetBlog() int64 {
	if m != nil {
		return m.Blog
	}
	return 0
}

type ArticleLine struct {
	Line                 int64                    `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	FkType               string                   `protobuf:"bytes,2,opt,name=fkType,proto3" json:"fkType,omitempty"`
	Props                map[string]*ArticleProps `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ArticleLine) Reset()         { *m = ArticleLine{} }
func (m *ArticleLine) String() string { return proto.CompactTextString(m) }
func (*ArticleLine) ProtoMessage()    {}
func (*ArticleLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{4}
}

func (m *ArticleLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleLine.Unmarshal(m, b)
}
func (m *ArticleLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleLine.Marshal(b, m, deterministic)
}
func (m *ArticleLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleLine.Merge(m, src)
}
func (m *ArticleLine) XXX_Size() int {
	return xxx_messageInfo_ArticleLine.Size(m)
}
func (m *ArticleLine) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleLine.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleLine proto.InternalMessageInfo

func (m *ArticleLine) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *ArticleLine) GetFkType() string {
	if m != nil {
		return m.FkType
	}
	return ""
}

func (m *ArticleLine) GetProps() map[string]*ArticleProps {
	if m != nil {
		return m.Props
	}
	return nil
}

type ArticleServiceRsBool struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceRsBool) Reset()         { *m = ArticleServiceRsBool{} }
func (m *ArticleServiceRsBool) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceRsBool) ProtoMessage()    {}
func (*ArticleServiceRsBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{5}
}

func (m *ArticleServiceRsBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceRsBool.Unmarshal(m, b)
}
func (m *ArticleServiceRsBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceRsBool.Marshal(b, m, deterministic)
}
func (m *ArticleServiceRsBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceRsBool.Merge(m, src)
}
func (m *ArticleServiceRsBool) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceRsBool.Size(m)
}
func (m *ArticleServiceRsBool) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceRsBool.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceRsBool proto.InternalMessageInfo

func (m *ArticleServiceRsBool) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ArticleUserModel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleUserModel) Reset()         { *m = ArticleUserModel{} }
func (m *ArticleUserModel) String() string { return proto.CompactTextString(m) }
func (*ArticleUserModel) ProtoMessage()    {}
func (*ArticleUserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{6}
}

func (m *ArticleUserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleUserModel.Unmarshal(m, b)
}
func (m *ArticleUserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleUserModel.Marshal(b, m, deterministic)
}
func (m *ArticleUserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleUserModel.Merge(m, src)
}
func (m *ArticleUserModel) XXX_Size() int {
	return xxx_messageInfo_ArticleUserModel.Size(m)
}
func (m *ArticleUserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleUserModel.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleUserModel proto.InternalMessageInfo

func (m *ArticleUserModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArticleCategoryModel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleCategoryModel) Reset()         { *m = ArticleCategoryModel{} }
func (m *ArticleCategoryModel) String() string { return proto.CompactTextString(m) }
func (*ArticleCategoryModel) ProtoMessage()    {}
func (*ArticleCategoryModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{7}
}

func (m *ArticleCategoryModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleCategoryModel.Unmarshal(m, b)
}
func (m *ArticleCategoryModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleCategoryModel.Marshal(b, m, deterministic)
}
func (m *ArticleCategoryModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleCategoryModel.Merge(m, src)
}
func (m *ArticleCategoryModel) XXX_Size() int {
	return xxx_messageInfo_ArticleCategoryModel.Size(m)
}
func (m *ArticleCategoryModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleCategoryModel.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleCategoryModel proto.InternalMessageInfo

func (m *ArticleCategoryModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArticleServiceModel struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FkUserId             int64                 `protobuf:"varint,4,opt,name=fkUserId,proto3" json:"fkUserId,omitempty"`
	FkCategoryId         int64                 `protobuf:"varint,5,opt,name=fkCategoryId,proto3" json:"fkCategoryId,omitempty"`
	UpdatedAt            string                `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	User                 *ArticleUserModel     `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Category             *ArticleCategoryModel `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ArticleServiceModel) Reset()         { *m = ArticleServiceModel{} }
func (m *ArticleServiceModel) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceModel) ProtoMessage()    {}
func (*ArticleServiceModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{8}
}

func (m *ArticleServiceModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceModel.Unmarshal(m, b)
}
func (m *ArticleServiceModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceModel.Marshal(b, m, deterministic)
}
func (m *ArticleServiceModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceModel.Merge(m, src)
}
func (m *ArticleServiceModel) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceModel.Size(m)
}
func (m *ArticleServiceModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceModel.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceModel proto.InternalMessageInfo

func (m *ArticleServiceModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServiceModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleServiceModel) GetFkUserId() int64 {
	if m != nil {
		return m.FkUserId
	}
	return 0
}

func (m *ArticleServiceModel) GetFkCategoryId() int64 {
	if m != nil {
		return m.FkCategoryId
	}
	return 0
}

func (m *ArticleServiceModel) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ArticleServiceModel) GetUser() *ArticleUserModel {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ArticleServiceModel) GetCategory() *ArticleCategoryModel {
	if m != nil {
		return m.Category
	}
	return nil
}

type ArticleUserServiceModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Offer                string   `protobuf:"bytes,6,opt,name=offer,proto3" json:"offer,omitempty"`
	Image                string   `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleUserServiceModel) Reset()         { *m = ArticleUserServiceModel{} }
func (m *ArticleUserServiceModel) String() string { return proto.CompactTextString(m) }
func (*ArticleUserServiceModel) ProtoMessage()    {}
func (*ArticleUserServiceModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{9}
}

func (m *ArticleUserServiceModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleUserServiceModel.Unmarshal(m, b)
}
func (m *ArticleUserServiceModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleUserServiceModel.Marshal(b, m, deterministic)
}
func (m *ArticleUserServiceModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleUserServiceModel.Merge(m, src)
}
func (m *ArticleUserServiceModel) XXX_Size() int {
	return xxx_messageInfo_ArticleUserServiceModel.Size(m)
}
func (m *ArticleUserServiceModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleUserServiceModel.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleUserServiceModel proto.InternalMessageInfo

func (m *ArticleUserServiceModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleUserServiceModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleUserServiceModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleUserServiceModel) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ArticleUserServiceModel) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ArticleUserServiceModel) GetOffer() string {
	if m != nil {
		return m.Offer
	}
	return ""
}

func (m *ArticleUserServiceModel) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ArticleServicePopularModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServicePopularModel) Reset()         { *m = ArticleServicePopularModel{} }
func (m *ArticleServicePopularModel) String() string { return proto.CompactTextString(m) }
func (*ArticleServicePopularModel) ProtoMessage()    {}
func (*ArticleServicePopularModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{10}
}

func (m *ArticleServicePopularModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServicePopularModel.Unmarshal(m, b)
}
func (m *ArticleServicePopularModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServicePopularModel.Marshal(b, m, deterministic)
}
func (m *ArticleServicePopularModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServicePopularModel.Merge(m, src)
}
func (m *ArticleServicePopularModel) XXX_Size() int {
	return xxx_messageInfo_ArticleServicePopularModel.Size(m)
}
func (m *ArticleServicePopularModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServicePopularModel.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServicePopularModel proto.InternalMessageInfo

func (m *ArticleServicePopularModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServicePopularModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServicePopularModel) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// Get all articles
type ArticleServiceGetAllRq struct {
	Offset               string   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                string   `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category             int64    `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	OrderLast            bool     `protobuf:"varint,4,opt,name=OrderLast,proto3" json:"OrderLast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetAllRq) Reset()         { *m = ArticleServiceGetAllRq{} }
func (m *ArticleServiceGetAllRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetAllRq) ProtoMessage()    {}
func (*ArticleServiceGetAllRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{11}
}

func (m *ArticleServiceGetAllRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetAllRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetAllRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetAllRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetAllRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetAllRq.Merge(m, src)
}
func (m *ArticleServiceGetAllRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetAllRq.Size(m)
}
func (m *ArticleServiceGetAllRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetAllRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetAllRq proto.InternalMessageInfo

func (m *ArticleServiceGetAllRq) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ArticleServiceGetAllRq) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *ArticleServiceGetAllRq) GetCategory() int64 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *ArticleServiceGetAllRq) GetOrderLast() bool {
	if m != nil {
		return m.OrderLast
	}
	return false
}

// Get all articles
type ArticleServiceGetAllUsersRq struct {
	Offset               string   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                string   `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	User                 int64    `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetAllUsersRq) Reset()         { *m = ArticleServiceGetAllUsersRq{} }
func (m *ArticleServiceGetAllUsersRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetAllUsersRq) ProtoMessage()    {}
func (*ArticleServiceGetAllUsersRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{12}
}

func (m *ArticleServiceGetAllUsersRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetAllUsersRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetAllUsersRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetAllUsersRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetAllUsersRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetAllUsersRq.Merge(m, src)
}
func (m *ArticleServiceGetAllUsersRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetAllUsersRq.Size(m)
}
func (m *ArticleServiceGetAllUsersRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetAllUsersRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetAllUsersRq proto.InternalMessageInfo

func (m *ArticleServiceGetAllUsersRq) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ArticleServiceGetAllUsersRq) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *ArticleServiceGetAllUsersRq) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

type ArticleServiceGetPopularRq struct {
	Offset               string   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                string   `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetPopularRq) Reset()         { *m = ArticleServiceGetPopularRq{} }
func (m *ArticleServiceGetPopularRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetPopularRq) ProtoMessage()    {}
func (*ArticleServiceGetPopularRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{13}
}

func (m *ArticleServiceGetPopularRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetPopularRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetPopularRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetPopularRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetPopularRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetPopularRq.Merge(m, src)
}
func (m *ArticleServiceGetPopularRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetPopularRq.Size(m)
}
func (m *ArticleServiceGetPopularRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetPopularRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetPopularRq proto.InternalMessageInfo

func (m *ArticleServiceGetPopularRq) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *ArticleServiceGetPopularRq) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

type ArticleServiceGetAllRs struct {
	Result               []*ArticleServiceModel `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Count                int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ArticleServiceGetAllRs) Reset()         { *m = ArticleServiceGetAllRs{} }
func (m *ArticleServiceGetAllRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetAllRs) ProtoMessage()    {}
func (*ArticleServiceGetAllRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{14}
}

func (m *ArticleServiceGetAllRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetAllRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetAllRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetAllRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetAllRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetAllRs.Merge(m, src)
}
func (m *ArticleServiceGetAllRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetAllRs.Size(m)
}
func (m *ArticleServiceGetAllRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetAllRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetAllRs proto.InternalMessageInfo

func (m *ArticleServiceGetAllRs) GetResult() []*ArticleServiceModel {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ArticleServiceGetAllRs) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ArticleServiceGetAllUserRs struct {
	Result               []*ArticleUserServiceModel `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Count                int64                      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ArticleServiceGetAllUserRs) Reset()         { *m = ArticleServiceGetAllUserRs{} }
func (m *ArticleServiceGetAllUserRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetAllUserRs) ProtoMessage()    {}
func (*ArticleServiceGetAllUserRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{15}
}

func (m *ArticleServiceGetAllUserRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetAllUserRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetAllUserRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetAllUserRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetAllUserRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetAllUserRs.Merge(m, src)
}
func (m *ArticleServiceGetAllUserRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetAllUserRs.Size(m)
}
func (m *ArticleServiceGetAllUserRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetAllUserRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetAllUserRs proto.InternalMessageInfo

func (m *ArticleServiceGetAllUserRs) GetResult() []*ArticleUserServiceModel {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ArticleServiceGetAllUserRs) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ArticleServiceGetPopularRs struct {
	Result               []*ArticleServicePopularModel `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Count                int64                         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ArticleServiceGetPopularRs) Reset()         { *m = ArticleServiceGetPopularRs{} }
func (m *ArticleServiceGetPopularRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetPopularRs) ProtoMessage()    {}
func (*ArticleServiceGetPopularRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{16}
}

func (m *ArticleServiceGetPopularRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetPopularRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetPopularRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetPopularRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetPopularRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetPopularRs.Merge(m, src)
}
func (m *ArticleServiceGetPopularRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetPopularRs.Size(m)
}
func (m *ArticleServiceGetPopularRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetPopularRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetPopularRs proto.InternalMessageInfo

func (m *ArticleServiceGetPopularRs) GetResult() []*ArticleServicePopularModel {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ArticleServiceGetPopularRs) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ArticleServiceGetBookRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetBookRq) Reset()         { *m = ArticleServiceGetBookRq{} }
func (m *ArticleServiceGetBookRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetBookRq) ProtoMessage()    {}
func (*ArticleServiceGetBookRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{17}
}

func (m *ArticleServiceGetBookRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetBookRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetBookRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetBookRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetBookRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetBookRq.Merge(m, src)
}
func (m *ArticleServiceGetBookRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetBookRq.Size(m)
}
func (m *ArticleServiceGetBookRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetBookRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetBookRq proto.InternalMessageInfo

func (m *ArticleServiceGetBookRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceGetBookRq) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

type ArticleServiceGetBookRs struct {
	Lines                []*ArticleLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Count                int64          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Views                int32          `protobuf:"varint,3,opt,name=Views,proto3" json:"Views,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArticleServiceGetBookRs) Reset()         { *m = ArticleServiceGetBookRs{} }
func (m *ArticleServiceGetBookRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetBookRs) ProtoMessage()    {}
func (*ArticleServiceGetBookRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{18}
}

func (m *ArticleServiceGetBookRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetBookRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetBookRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetBookRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetBookRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetBookRs.Merge(m, src)
}
func (m *ArticleServiceGetBookRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetBookRs.Size(m)
}
func (m *ArticleServiceGetBookRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetBookRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetBookRs proto.InternalMessageInfo

func (m *ArticleServiceGetBookRs) GetLines() []*ArticleLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ArticleServiceGetBookRs) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ArticleServiceGetBookRs) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

// Get article single
type ArticleServiceGetRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetRq) Reset()         { *m = ArticleServiceGetRq{} }
func (m *ArticleServiceGetRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetRq) ProtoMessage()    {}
func (*ArticleServiceGetRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{19}
}

func (m *ArticleServiceGetRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetRq.Merge(m, src)
}
func (m *ArticleServiceGetRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetRq.Size(m)
}
func (m *ArticleServiceGetRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetRq proto.InternalMessageInfo

func (m *ArticleServiceGetRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArticleServiceGetRs struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FkUserId             int64                 `protobuf:"varint,4,opt,name=fkUserId,proto3" json:"fkUserId,omitempty"`
	FkCategoryId         int64                 `protobuf:"varint,5,opt,name=fkCategoryId,proto3" json:"fkCategoryId,omitempty"`
	UpdatedAt            string                `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	User                 *ArticleUserModel     `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Category             *ArticleCategoryModel `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Tags                 []*ArticleTag         `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ArticleServiceGetRs) Reset()         { *m = ArticleServiceGetRs{} }
func (m *ArticleServiceGetRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetRs) ProtoMessage()    {}
func (*ArticleServiceGetRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{20}
}

func (m *ArticleServiceGetRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetRs.Merge(m, src)
}
func (m *ArticleServiceGetRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetRs.Size(m)
}
func (m *ArticleServiceGetRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetRs proto.InternalMessageInfo

func (m *ArticleServiceGetRs) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceGetRs) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServiceGetRs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleServiceGetRs) GetFkUserId() int64 {
	if m != nil {
		return m.FkUserId
	}
	return 0
}

func (m *ArticleServiceGetRs) GetFkCategoryId() int64 {
	if m != nil {
		return m.FkCategoryId
	}
	return 0
}

func (m *ArticleServiceGetRs) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ArticleServiceGetRs) GetUser() *ArticleUserModel {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ArticleServiceGetRs) GetCategory() *ArticleCategoryModel {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ArticleServiceGetRs) GetTags() []*ArticleTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ArticleServiceGetCommentsRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetCommentsRq) Reset()         { *m = ArticleServiceGetCommentsRq{} }
func (m *ArticleServiceGetCommentsRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetCommentsRq) ProtoMessage()    {}
func (*ArticleServiceGetCommentsRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{21}
}

func (m *ArticleServiceGetCommentsRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetCommentsRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetCommentsRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetCommentsRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetCommentsRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetCommentsRq.Merge(m, src)
}
func (m *ArticleServiceGetCommentsRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetCommentsRq.Size(m)
}
func (m *ArticleServiceGetCommentsRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetCommentsRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetCommentsRq proto.InternalMessageInfo

func (m *ArticleServiceGetCommentsRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceGetCommentsRq) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

type ArticleServiceGetCommentsLastRq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceGetCommentsLastRq) Reset()         { *m = ArticleServiceGetCommentsLastRq{} }
func (m *ArticleServiceGetCommentsLastRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetCommentsLastRq) ProtoMessage()    {}
func (*ArticleServiceGetCommentsLastRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{22}
}

func (m *ArticleServiceGetCommentsLastRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRq.Unmarshal(m, b)
}
func (m *ArticleServiceGetCommentsLastRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetCommentsLastRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetCommentsLastRq.Merge(m, src)
}
func (m *ArticleServiceGetCommentsLastRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRq.Size(m)
}
func (m *ArticleServiceGetCommentsLastRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetCommentsLastRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetCommentsLastRq proto.InternalMessageInfo

type ArticleServiceGetCommentsRs struct {
	Comments             []*ArticleComment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ArticleServiceGetCommentsRs) Reset()         { *m = ArticleServiceGetCommentsRs{} }
func (m *ArticleServiceGetCommentsRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetCommentsRs) ProtoMessage()    {}
func (*ArticleServiceGetCommentsRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{23}
}

func (m *ArticleServiceGetCommentsRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetCommentsRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetCommentsRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetCommentsRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetCommentsRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetCommentsRs.Merge(m, src)
}
func (m *ArticleServiceGetCommentsRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetCommentsRs.Size(m)
}
func (m *ArticleServiceGetCommentsRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetCommentsRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetCommentsRs proto.InternalMessageInfo

func (m *ArticleServiceGetCommentsRs) GetComments() []*ArticleComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type ArticleServiceGetCommentsLastRs struct {
	Comments             []*ArticleCommentLast `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ArticleServiceGetCommentsLastRs) Reset()         { *m = ArticleServiceGetCommentsLastRs{} }
func (m *ArticleServiceGetCommentsLastRs) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceGetCommentsLastRs) ProtoMessage()    {}
func (*ArticleServiceGetCommentsLastRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{24}
}

func (m *ArticleServiceGetCommentsLastRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRs.Unmarshal(m, b)
}
func (m *ArticleServiceGetCommentsLastRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRs.Marshal(b, m, deterministic)
}
func (m *ArticleServiceGetCommentsLastRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceGetCommentsLastRs.Merge(m, src)
}
func (m *ArticleServiceGetCommentsLastRs) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceGetCommentsLastRs.Size(m)
}
func (m *ArticleServiceGetCommentsLastRs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceGetCommentsLastRs.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceGetCommentsLastRs proto.InternalMessageInfo

func (m *ArticleServiceGetCommentsLastRs) GetComments() []*ArticleCommentLast {
	if m != nil {
		return m.Comments
	}
	return nil
}

// Create article single
type ArticleServiceCreateRq struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FkUserId             int64    `protobuf:"varint,3,opt,name=fkUserId,proto3" json:"fkUserId,omitempty"`
	FkCategoryId         int64    `protobuf:"varint,4,opt,name=fkCategoryId,proto3" json:"fkCategoryId,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Offer                float32  `protobuf:"fixed32,6,opt,name=offer,proto3" json:"offer,omitempty"`
	FileNames            []string `protobuf:"bytes,7,rep,name=fileNames,proto3" json:"fileNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceCreateRq) Reset()         { *m = ArticleServiceCreateRq{} }
func (m *ArticleServiceCreateRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceCreateRq) ProtoMessage()    {}
func (*ArticleServiceCreateRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{25}
}

func (m *ArticleServiceCreateRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceCreateRq.Unmarshal(m, b)
}
func (m *ArticleServiceCreateRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceCreateRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceCreateRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceCreateRq.Merge(m, src)
}
func (m *ArticleServiceCreateRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceCreateRq.Size(m)
}
func (m *ArticleServiceCreateRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceCreateRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceCreateRq proto.InternalMessageInfo

func (m *ArticleServiceCreateRq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServiceCreateRq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleServiceCreateRq) GetFkUserId() int64 {
	if m != nil {
		return m.FkUserId
	}
	return 0
}

func (m *ArticleServiceCreateRq) GetFkCategoryId() int64 {
	if m != nil {
		return m.FkCategoryId
	}
	return 0
}

func (m *ArticleServiceCreateRq) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ArticleServiceCreateRq) GetOffer() float32 {
	if m != nil {
		return m.Offer
	}
	return 0
}

func (m *ArticleServiceCreateRq) GetFileNames() []string {
	if m != nil {
		return m.FileNames
	}
	return nil
}

// Update article single
type ArticleServiceUpdateRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FkCategoryId         int64    `protobuf:"varint,5,opt,name=fkCategoryId,proto3" json:"fkCategoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceUpdateRq) Reset()         { *m = ArticleServiceUpdateRq{} }
func (m *ArticleServiceUpdateRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceUpdateRq) ProtoMessage()    {}
func (*ArticleServiceUpdateRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{26}
}

func (m *ArticleServiceUpdateRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceUpdateRq.Unmarshal(m, b)
}
func (m *ArticleServiceUpdateRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceUpdateRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceUpdateRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceUpdateRq.Merge(m, src)
}
func (m *ArticleServiceUpdateRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceUpdateRq.Size(m)
}
func (m *ArticleServiceUpdateRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceUpdateRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceUpdateRq proto.InternalMessageInfo

func (m *ArticleServiceUpdateRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceUpdateRq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleServiceUpdateRq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ArticleServiceUpdateRq) GetFkCategoryId() int64 {
	if m != nil {
		return m.FkCategoryId
	}
	return 0
}

// Delete article single
type ArticleServiceDeleteRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceDeleteRq) Reset()         { *m = ArticleServiceDeleteRq{} }
func (m *ArticleServiceDeleteRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceDeleteRq) ProtoMessage()    {}
func (*ArticleServiceDeleteRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{27}
}

func (m *ArticleServiceDeleteRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceDeleteRq.Unmarshal(m, b)
}
func (m *ArticleServiceDeleteRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceDeleteRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceDeleteRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceDeleteRq.Merge(m, src)
}
func (m *ArticleServiceDeleteRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceDeleteRq.Size(m)
}
func (m *ArticleServiceDeleteRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceDeleteRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceDeleteRq proto.InternalMessageInfo

func (m *ArticleServiceDeleteRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Active Article single
type ArticleServiceActiveRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceActiveRq) Reset()         { *m = ArticleServiceActiveRq{} }
func (m *ArticleServiceActiveRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceActiveRq) ProtoMessage()    {}
func (*ArticleServiceActiveRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{28}
}

func (m *ArticleServiceActiveRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceActiveRq.Unmarshal(m, b)
}
func (m *ArticleServiceActiveRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceActiveRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceActiveRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceActiveRq.Merge(m, src)
}
func (m *ArticleServiceActiveRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceActiveRq.Size(m)
}
func (m *ArticleServiceActiveRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceActiveRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceActiveRq proto.InternalMessageInfo

func (m *ArticleServiceActiveRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceActiveRq) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// Active Article public
type ArticleServicePublicRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServicePublicRq) Reset()         { *m = ArticleServicePublicRq{} }
func (m *ArticleServicePublicRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServicePublicRq) ProtoMessage()    {}
func (*ArticleServicePublicRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{29}
}

func (m *ArticleServicePublicRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServicePublicRq.Unmarshal(m, b)
}
func (m *ArticleServicePublicRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServicePublicRq.Marshal(b, m, deterministic)
}
func (m *ArticleServicePublicRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServicePublicRq.Merge(m, src)
}
func (m *ArticleServicePublicRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServicePublicRq.Size(m)
}
func (m *ArticleServicePublicRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServicePublicRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServicePublicRq proto.InternalMessageInfo

func (m *ArticleServicePublicRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArticleServiceViewRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleServiceViewRq) Reset()         { *m = ArticleServiceViewRq{} }
func (m *ArticleServiceViewRq) String() string { return proto.CompactTextString(m) }
func (*ArticleServiceViewRq) ProtoMessage()    {}
func (*ArticleServiceViewRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ca33b1f5292af39, []int{30}
}

func (m *ArticleServiceViewRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleServiceViewRq.Unmarshal(m, b)
}
func (m *ArticleServiceViewRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleServiceViewRq.Marshal(b, m, deterministic)
}
func (m *ArticleServiceViewRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleServiceViewRq.Merge(m, src)
}
func (m *ArticleServiceViewRq) XXX_Size() int {
	return xxx_messageInfo_ArticleServiceViewRq.Size(m)
}
func (m *ArticleServiceViewRq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleServiceViewRq.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleServiceViewRq proto.InternalMessageInfo

func (m *ArticleServiceViewRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleServiceViewRq) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

func init() {
	proto.RegisterType((*ArticleProps)(nil), "proto.ArticleProps")
	proto.RegisterType((*ArticleTag)(nil), "proto.ArticleTag")
	proto.RegisterType((*ArticleComment)(nil), "proto.ArticleComment")
	proto.RegisterType((*ArticleCommentLast)(nil), "proto.ArticleCommentLast")
	proto.RegisterType((*ArticleLine)(nil), "proto.ArticleLine")
	proto.RegisterMapType((map[string]*ArticleProps)(nil), "proto.ArticleLine.PropsEntry")
	proto.RegisterType((*ArticleServiceRsBool)(nil), "proto.ArticleServiceRsBool")
	proto.RegisterType((*ArticleUserModel)(nil), "proto.ArticleUserModel")
	proto.RegisterType((*ArticleCategoryModel)(nil), "proto.ArticleCategoryModel")
	proto.RegisterType((*ArticleServiceModel)(nil), "proto.ArticleServiceModel")
	proto.RegisterType((*ArticleUserServiceModel)(nil), "proto.ArticleUserServiceModel")
	proto.RegisterType((*ArticleServicePopularModel)(nil), "proto.ArticleServicePopularModel")
	proto.RegisterType((*ArticleServiceGetAllRq)(nil), "proto.ArticleServiceGetAllRq")
	proto.RegisterType((*ArticleServiceGetAllUsersRq)(nil), "proto.ArticleServiceGetAllUsersRq")
	proto.RegisterType((*ArticleServiceGetPopularRq)(nil), "proto.ArticleServiceGetPopularRq")
	proto.RegisterType((*ArticleServiceGetAllRs)(nil), "proto.ArticleServiceGetAllRs")
	proto.RegisterType((*ArticleServiceGetAllUserRs)(nil), "proto.ArticleServiceGetAllUserRs")
	proto.RegisterType((*ArticleServiceGetPopularRs)(nil), "proto.ArticleServiceGetPopularRs")
	proto.RegisterType((*ArticleServiceGetBookRq)(nil), "proto.ArticleServiceGetBookRq")
	proto.RegisterType((*ArticleServiceGetBookRs)(nil), "proto.ArticleServiceGetBookRs")
	proto.RegisterType((*ArticleServiceGetRq)(nil), "proto.ArticleServiceGetRq")
	proto.RegisterType((*ArticleServiceGetRs)(nil), "proto.ArticleServiceGetRs")
	proto.RegisterType((*ArticleServiceGetCommentsRq)(nil), "proto.ArticleServiceGetCommentsRq")
	proto.RegisterType((*ArticleServiceGetCommentsLastRq)(nil), "proto.ArticleServiceGetCommentsLastRq")
	proto.RegisterType((*ArticleServiceGetCommentsRs)(nil), "proto.ArticleServiceGetCommentsRs")
	proto.RegisterType((*ArticleServiceGetCommentsLastRs)(nil), "proto.ArticleServiceGetCommentsLastRs")
	proto.RegisterType((*ArticleServiceCreateRq)(nil), "proto.ArticleServiceCreateRq")
	proto.RegisterType((*ArticleServiceUpdateRq)(nil), "proto.ArticleServiceUpdateRq")
	proto.RegisterType((*ArticleServiceDeleteRq)(nil), "proto.ArticleServiceDeleteRq")
	proto.RegisterType((*ArticleServiceActiveRq)(nil), "proto.ArticleServiceActiveRq")
	proto.RegisterType((*ArticleServicePublicRq)(nil), "proto.ArticleServicePublicRq")
	proto.RegisterType((*ArticleServiceViewRq)(nil), "proto.ArticleServiceViewRq")
}

func init() {
	proto.RegisterFile("proto/articleService.proto", fileDescriptor_7ca33b1f5292af39)
}

var fileDescriptor_7ca33b1f5292af39 = []byte{
	// 1142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcd, 0x6e, 0x23, 0xc5,
	0x13, 0x97, 0x3d, 0x8e, 0x3f, 0x2a, 0xd1, 0xfe, 0xf7, 0x5f, 0x1b, 0xb2, 0xc3, 0x64, 0x37, 0x24,
	0x2d, 0xed, 0x2a, 0x80, 0x14, 0x20, 0x2b, 0x60, 0x59, 0x69, 0x25, 0xbc, 0x09, 0x44, 0x59, 0xed,
	0x42, 0xd4, 0x24, 0x88, 0x1b, 0x4c, 0x66, 0xda, 0xd6, 0xe0, 0xb1, 0xdb, 0x9e, 0x1e, 0x07, 0xf9,
	0xc6, 0x81, 0x23, 0x2f, 0xc1, 0x83, 0x70, 0xe0, 0xc6, 0x33, 0xf0, 0x12, 0xbc, 0x02, 0xea, 0x8f,
	0x19, 0x7b, 0xc6, 0x33, 0x63, 0x07, 0x09, 0x4e, 0x9c, 0xdc, 0x55, 0x5d, 0x5d, 0xf5, 0xeb, 0xaa,
	0x5f, 0x55, 0x8f, 0xc1, 0x19, 0x47, 0x3c, 0xe6, 0xef, 0xb9, 0x51, 0x1c, 0x78, 0x21, 0xfb, 0x8a,
	0x45, 0x37, 0x81, 0xc7, 0x8e, 0x94, 0x12, 0x37, 0xd4, 0x0f, 0x79, 0x0a, 0x5b, 0x5d, 0xbd, 0x7d,
	0x11, 0xf1, 0xb1, 0x40, 0x84, 0xc6, 0x38, 0xe2, 0x63, 0xbb, 0xb6, 0x5f, 0x3b, 0xec, 0x50, 0xb5,
	0xc6, 0x6d, 0xd8, 0xb8, 0x71, 0xc3, 0x29, 0xb3, 0xeb, 0x4a, 0xa9, 0x05, 0xb2, 0x07, 0x60, 0x4e,
	0x5e, 0xba, 0x7d, 0xbc, 0x0b, 0x56, 0xec, 0xf6, 0xcd, 0x31, 0xb9, 0x24, 0x31, 0xdc, 0x31, 0xfb,
	0x27, 0x7c, 0x38, 0x64, 0xa3, 0x18, 0xef, 0x40, 0x3d, 0xf0, 0x95, 0x89, 0x45, 0xeb, 0x81, 0x8f,
	0x0f, 0xa0, 0xe3, 0x45, 0xcc, 0x8d, 0x99, 0xdf, 0x8d, 0x8d, 0xef, 0xb9, 0x02, 0xf7, 0x61, 0xd3,
	0x67, 0xc2, 0x8b, 0x82, 0x71, 0x1c, 0xf0, 0x91, 0x6d, 0xa9, 0xfd, 0x45, 0x95, 0xc4, 0x3a, 0x72,
	0x87, 0xcc, 0x6e, 0x68, 0xac, 0x72, 0x4d, 0x7e, 0xae, 0x01, 0x66, 0xc3, 0xbe, 0x72, 0xc5, 0xbf,
	0x12, 0x5a, 0xea, 0xae, 0x43, 0xde, 0xb7, 0x37, 0x54, 0x14, 0xb5, 0x26, 0xbf, 0xd6, 0x60, 0xd3,
	0xc0, 0x79, 0x15, 0x8c, 0x94, 0x4d, 0x18, 0x8c, 0x98, 0x41, 0xa2, 0xd6, 0xb8, 0x03, 0xcd, 0xde,
	0xe0, 0x72, 0x36, 0x4e, 0xf2, 0x6b, 0x24, 0x7c, 0x02, 0xb2, 0x46, 0x63, 0x61, 0x5b, 0xfb, 0xd6,
	0xe1, 0xe6, 0xf1, 0x43, 0x5d, 0xb8, 0xa3, 0x05, 0x77, 0x47, 0xaa, 0x66, 0x9f, 0x8d, 0xe2, 0x68,
	0x46, 0xb5, 0xad, 0xf3, 0x1a, 0x60, 0xae, 0x94, 0x55, 0x19, 0xb0, 0x59, 0x52, 0x95, 0x01, 0x9b,
	0xe1, 0xdb, 0x8b, 0xb5, 0xdc, 0x3c, 0xbe, 0x97, 0x75, 0xaa, 0x8e, 0x9a, 0x02, 0x3f, 0xab, 0x3f,
	0xad, 0x91, 0xf7, 0x61, 0xbb, 0x9b, 0x61, 0x0f, 0x15, 0x2f, 0x38, 0x0f, 0xd1, 0x86, 0x96, 0x98,
	0x7a, 0x1e, 0x13, 0x42, 0x39, 0x6f, 0xd3, 0x44, 0x24, 0x8f, 0xe1, 0xae, 0x39, 0x71, 0x25, 0x58,
	0xf4, 0x9a, 0xfb, 0x2c, 0x4c, 0xb3, 0x55, 0x5b, 0x28, 0xd4, 0x3b, 0xa9, 0xe7, 0x13, 0x37, 0x66,
	0x7d, 0x1e, 0xcd, 0xca, 0x6d, 0x7f, 0xa9, 0xc3, 0xbd, 0x2c, 0x0c, 0x6d, 0x9b, 0xaf, 0xea, 0x36,
	0x6c, 0xc4, 0x41, 0x1c, 0xa6, 0x44, 0x55, 0xc2, 0x1a, 0xd5, 0x74, 0xa0, 0xdd, 0x1b, 0x48, 0xb8,
	0xe7, 0xbe, 0xaa, 0xa8, 0x45, 0x53, 0x19, 0x09, 0x6c, 0xf5, 0x06, 0x09, 0xc4, 0x73, 0xdf, 0x54,
	0x37, 0xa3, 0x93, 0x6c, 0x9a, 0x8e, 0x7d, 0xc3, 0xa6, 0xa6, 0x66, 0x53, 0xaa, 0xc0, 0x77, 0xa1,
	0x31, 0x15, 0x2c, 0xb2, 0x5b, 0x2a, 0xe3, 0xf7, 0xb3, 0x19, 0x4f, 0x93, 0x44, 0x95, 0x11, 0x7e,
	0x0c, 0x6d, 0xcf, 0x38, 0xb6, 0xdb, 0xea, 0xc0, 0x6e, 0xf6, 0x40, 0x26, 0x5b, 0x34, 0x35, 0x26,
	0xbf, 0xd5, 0xe0, 0xfe, 0x82, 0xcf, 0x7f, 0x24, 0x4f, 0x99, 0x7b, 0x36, 0xf2, 0xf7, 0xdc, 0x96,
	0x7c, 0x0d, 0x3c, 0xa6, 0x52, 0xd4, 0xa1, 0x5a, 0x90, 0x5a, 0xde, 0xeb, 0xb1, 0xc8, 0xe4, 0x45,
	0x0b, 0x52, 0x1b, 0x0c, 0xdd, 0x3e, 0x53, 0x49, 0xe9, 0x50, 0x2d, 0x90, 0xef, 0xc0, 0xc9, 0x96,
	0xf9, 0x82, 0x8f, 0xa7, 0xa1, 0x1b, 0xdd, 0xe6, 0x16, 0x19, 0x8c, 0x56, 0x0e, 0x23, 0xf9, 0xb1,
	0x06, 0x3b, 0xd9, 0x10, 0x67, 0x2c, 0xee, 0x86, 0x21, 0x9d, 0xc8, 0x36, 0xe4, 0xbd, 0x9e, 0x60,
	0xb1, 0xa1, 0x9e, 0x91, 0x64, 0x98, 0x30, 0x18, 0x06, 0xc9, 0x98, 0xd0, 0x82, 0xa4, 0x4c, 0x5a,
	0x27, 0x4b, 0x53, 0x26, 0x91, 0x25, 0x84, 0x2f, 0x23, 0x9f, 0x45, 0x72, 0xf2, 0xa8, 0x34, 0xb5,
	0xe9, 0x5c, 0x41, 0xbe, 0x85, 0xdd, 0x22, 0x04, 0xb2, 0x68, 0xe2, 0xd6, 0x30, 0xd0, 0x70, 0x4b,
	0x43, 0x50, 0x6b, 0xf2, 0x32, 0x9f, 0xc5, 0x33, 0x16, 0x9b, 0x44, 0xde, 0xd6, 0x3f, 0xb9, 0x2e,
	0x49, 0x97, 0xc0, 0x63, 0x68, 0x46, 0x4c, 0x4c, 0x43, 0xe9, 0x47, 0x8e, 0x27, 0x27, 0x4b, 0xd3,
	0x45, 0xfe, 0x51, 0x63, 0x29, 0x63, 0x78, 0x7c, 0x3a, 0xd2, 0x31, 0x2c, 0xaa, 0x05, 0xf2, 0x7d,
	0x01, 0x5e, 0x93, 0x10, 0x2a, 0xf0, 0xa3, 0x5c, 0x9c, 0xbd, 0xe5, 0xfe, 0xb9, 0x45, 0xac, 0x61,
	0x45, 0x6e, 0x04, 0x7e, 0x92, 0x8b, 0x75, 0x50, 0x78, 0xa7, 0x45, 0x52, 0xae, 0x08, 0xf7, 0x3c,
	0xed, 0xc9, 0x79, 0xb8, 0x17, 0x9c, 0x0f, 0xe8, 0x64, 0x89, 0xcd, 0xf2, 0xf5, 0xe0, 0x7c, 0x60,
	0xd2, 0xaf, 0xd6, 0x84, 0x97, 0x1d, 0x17, 0x78, 0x28, 0xcb, 0x35, 0x62, 0xc2, 0x20, 0xc5, 0xe5,
	0xc7, 0x81, 0x6a, 0x83, 0x62, 0x64, 0x52, 0xfb, 0x75, 0xc0, 0x7e, 0x10, 0x8a, 0x39, 0x1b, 0x54,
	0x0b, 0xe4, 0x51, 0x7e, 0xce, 0x9e, 0xb1, 0x78, 0x19, 0x2b, 0xf9, 0xbd, 0x5e, 0x64, 0x27, 0xfe,
	0x9b, 0xc7, 0x0b, 0x43, 0xe0, 0x11, 0x34, 0x62, 0xb7, 0x2f, 0xec, 0x8e, 0xaa, 0xcf, 0xff, 0xb3,
	0x87, 0x2e, 0xdd, 0x3e, 0x55, 0xdb, 0xa4, 0x5b, 0x30, 0x0d, 0xcc, 0x87, 0x8b, 0x58, 0x93, 0x25,
	0x07, 0xf0, 0x56, 0xa9, 0x0b, 0x39, 0x71, 0xe8, 0x84, 0x5c, 0x54, 0x45, 0x11, 0xf8, 0x01, 0xb4,
	0x3d, 0x23, 0x19, 0x3e, 0xbd, 0x91, 0xbb, 0xa4, 0xde, 0xa5, 0xa9, 0x19, 0xf9, 0x66, 0x55, 0x50,
	0x81, 0x1f, 0x2e, 0x79, 0x7d, 0xb3, 0xd0, 0xab, 0x32, 0x9f, 0x7b, 0xfe, 0x63, 0x69, 0x44, 0x9f,
	0xa8, 0x0f, 0x33, 0x3a, 0x99, 0xf3, 0xa9, 0x56, 0xc1, 0xa7, 0x7a, 0x35, 0x9f, 0xac, 0x15, 0x7c,
	0x6a, 0x14, 0xf0, 0x29, 0xf3, 0xb2, 0xd5, 0x0b, 0x5f, 0xb6, 0x7a, 0xf2, 0xb2, 0x3d, 0x80, 0x4e,
	0x2f, 0x08, 0xd9, 0x17, 0xee, 0x90, 0x09, 0xbb, 0xb5, 0x6f, 0x49, 0xee, 0xa5, 0x0a, 0xf2, 0xd3,
	0xd2, 0xe5, 0xae, 0x14, 0x2f, 0x0b, 0x4a, 0xfd, 0x77, 0x9b, 0x67, 0x8d, 0x06, 0x21, 0x87, 0x79,
	0x14, 0xa7, 0x2c, 0x64, 0x45, 0x28, 0xc8, 0xa7, 0x79, 0xcb, 0xae, 0x17, 0x07, 0x37, 0x45, 0x78,
	0x77, 0xa0, 0xe9, 0xaa, 0x3d, 0x05, 0xb8, 0x4d, 0x8d, 0xb4, 0x1c, 0xeb, 0x62, 0x7a, 0x1d, 0x06,
	0x5e, 0x41, 0xac, 0x67, 0xf9, 0x8f, 0x4d, 0x39, 0x94, 0xd6, 0x6b, 0x82, 0xe3, 0x3f, 0x5b, 0xe9,
	0xdf, 0x0d, 0x73, 0x18, 0x2f, 0x61, 0x73, 0xe1, 0x69, 0x45, 0x52, 0x38, 0xcc, 0x33, 0x8f, 0xaf,
	0x73, 0xb0, 0xc2, 0x86, 0x0a, 0xfc, 0x1c, 0x9a, 0x5a, 0xc6, 0x87, 0x15, 0xc6, 0x74, 0xe2, 0x54,
	0x6e, 0x0b, 0xa4, 0x00, 0xf3, 0xb7, 0x07, 0x4b, 0x03, 0xa7, 0x0f, 0xb7, 0xb3, 0xd2, 0x44, 0xe0,
	0x73, 0xb0, 0xce, 0x58, 0x8c, 0x4e, 0x99, 0x25, 0x9d, 0x38, 0xe5, 0x7b, 0x02, 0xaf, 0x54, 0xc2,
	0x92, 0x2e, 0x2e, 0x4f, 0xd8, 0x7c, 0x3e, 0x39, 0xab, 0x6d, 0x04, 0xba, 0xf0, 0xbf, 0xdc, 0x70,
	0xc0, 0xc7, 0xab, 0x8e, 0xe9, 0xb9, 0xe5, 0xac, 0x67, 0x27, 0xf0, 0x1c, 0x5a, 0xe6, 0x69, 0xc4,
	0xbd, 0xb2, 0x23, 0xfa, 0xdd, 0x75, 0xaa, 0xf7, 0x05, 0x9e, 0x42, 0x53, 0xb7, 0x64, 0x49, 0x7d,
	0x93, 0x7e, 0x75, 0x76, 0x0b, 0xb7, 0xcd, 0xff, 0xa3, 0x53, 0x68, 0xea, 0x96, 0x2a, 0xf1, 0x92,
	0xf4, 0xdb, 0x4a, 0x2f, 0xba, 0xdd, 0x4a, 0xbc, 0x24, 0xbd, 0x58, 0xed, 0xe5, 0x04, 0x5a, 0x5d,
	0xdf, 0x97, 0xbd, 0x84, 0xc5, 0x76, 0xba, 0xcd, 0xaa, 0x9d, 0xbc, 0x84, 0xad, 0x4b, 0xde, 0xef,
	0x87, 0xa6, 0x7b, 0x4b, 0x00, 0x25, 0xad, 0xbd, 0xf2, 0x5a, 0x7a, 0xa4, 0x97, 0x78, 0x49, 0xe6,
	0x7d, 0xa5, 0x97, 0xeb, 0xa6, 0xda, 0x7b, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x18,
	0xce, 0x33, 0xe5, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleServiceClient interface {
	GetAllUsers(ctx context.Context, in *ArticleServiceGetAllUsersRq, opts ...grpc.CallOption) (*ArticleServiceGetAllUserRs, error)
	GetAll(ctx context.Context, in *ArticleServiceGetAllRq, opts ...grpc.CallOption) (*ArticleServiceGetAllRs, error)
	GetPopular(ctx context.Context, in *ArticleServiceGetPopularRq, opts ...grpc.CallOption) (*ArticleServiceGetPopularRs, error)
	Get(ctx context.Context, in *ArticleServiceGetRq, opts ...grpc.CallOption) (*ArticleServiceGetRs, error)
	GetComments(ctx context.Context, in *ArticleServiceGetCommentsRq, opts ...grpc.CallOption) (*ArticleServiceGetCommentsRs, error)
	GetCommentsLast(ctx context.Context, in *ArticleServiceGetCommentsLastRq, opts ...grpc.CallOption) (*ArticleServiceGetCommentsLastRs, error)
	GetBook(ctx context.Context, in *ArticleServiceGetBookRq, opts ...grpc.CallOption) (*ArticleServiceGetBookRs, error)
	Update(ctx context.Context, in *ArticleServiceUpdateRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
	Delete(ctx context.Context, in *ArticleServiceDeleteRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
	Active(ctx context.Context, in *ArticleServiceActiveRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
	AddView(ctx context.Context, in *ArticleServiceViewRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
	TogglePublic(ctx context.Context, in *ArticleServicePublicRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
	Create(ctx context.Context, in *ArticleServiceCreateRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetAllUsers(ctx context.Context, in *ArticleServiceGetAllUsersRq, opts ...grpc.CallOption) (*ArticleServiceGetAllUserRs, error) {
	out := new(ArticleServiceGetAllUserRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetAll(ctx context.Context, in *ArticleServiceGetAllRq, opts ...grpc.CallOption) (*ArticleServiceGetAllRs, error) {
	out := new(ArticleServiceGetAllRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetPopular(ctx context.Context, in *ArticleServiceGetPopularRq, opts ...grpc.CallOption) (*ArticleServiceGetPopularRs, error) {
	out := new(ArticleServiceGetPopularRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetPopular", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) Get(ctx context.Context, in *ArticleServiceGetRq, opts ...grpc.CallOption) (*ArticleServiceGetRs, error) {
	out := new(ArticleServiceGetRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetComments(ctx context.Context, in *ArticleServiceGetCommentsRq, opts ...grpc.CallOption) (*ArticleServiceGetCommentsRs, error) {
	out := new(ArticleServiceGetCommentsRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetCommentsLast(ctx context.Context, in *ArticleServiceGetCommentsLastRq, opts ...grpc.CallOption) (*ArticleServiceGetCommentsLastRs, error) {
	out := new(ArticleServiceGetCommentsLastRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetCommentsLast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetBook(ctx context.Context, in *ArticleServiceGetBookRq, opts ...grpc.CallOption) (*ArticleServiceGetBookRs, error) {
	out := new(ArticleServiceGetBookRs)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) Update(ctx context.Context, in *ArticleServiceUpdateRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) Delete(ctx context.Context, in *ArticleServiceDeleteRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) Active(ctx context.Context, in *ArticleServiceActiveRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/Active", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) AddView(ctx context.Context, in *ArticleServiceViewRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/AddView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) TogglePublic(ctx context.Context, in *ArticleServicePublicRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/TogglePublic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) Create(ctx context.Context, in *ArticleServiceCreateRq, opts ...grpc.CallOption) (*ArticleServiceRsBool, error) {
	out := new(ArticleServiceRsBool)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
type ArticleServiceServer interface {
	GetAllUsers(context.Context, *ArticleServiceGetAllUsersRq) (*ArticleServiceGetAllUserRs, error)
	GetAll(context.Context, *ArticleServiceGetAllRq) (*ArticleServiceGetAllRs, error)
	GetPopular(context.Context, *ArticleServiceGetPopularRq) (*ArticleServiceGetPopularRs, error)
	Get(context.Context, *ArticleServiceGetRq) (*ArticleServiceGetRs, error)
	GetComments(context.Context, *ArticleServiceGetCommentsRq) (*ArticleServiceGetCommentsRs, error)
	GetCommentsLast(context.Context, *ArticleServiceGetCommentsLastRq) (*ArticleServiceGetCommentsLastRs, error)
	GetBook(context.Context, *ArticleServiceGetBookRq) (*ArticleServiceGetBookRs, error)
	Update(context.Context, *ArticleServiceUpdateRq) (*ArticleServiceRsBool, error)
	Delete(context.Context, *ArticleServiceDeleteRq) (*ArticleServiceRsBool, error)
	Active(context.Context, *ArticleServiceActiveRq) (*ArticleServiceRsBool, error)
	AddView(context.Context, *ArticleServiceViewRq) (*ArticleServiceRsBool, error)
	TogglePublic(context.Context, *ArticleServicePublicRq) (*ArticleServiceRsBool, error)
	Create(context.Context, *ArticleServiceCreateRq) (*ArticleServiceRsBool, error)
}

// UnimplementedArticleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServiceServer struct {
}

func (*UnimplementedArticleServiceServer) GetAllUsers(ctx context.Context, req *ArticleServiceGetAllUsersRq) (*ArticleServiceGetAllUserRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (*UnimplementedArticleServiceServer) GetAll(ctx context.Context, req *ArticleServiceGetAllRq) (*ArticleServiceGetAllRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedArticleServiceServer) GetPopular(ctx context.Context, req *ArticleServiceGetPopularRq) (*ArticleServiceGetPopularRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopular not implemented")
}
func (*UnimplementedArticleServiceServer) Get(ctx context.Context, req *ArticleServiceGetRq) (*ArticleServiceGetRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedArticleServiceServer) GetComments(ctx context.Context, req *ArticleServiceGetCommentsRq) (*ArticleServiceGetCommentsRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}
func (*UnimplementedArticleServiceServer) GetCommentsLast(ctx context.Context, req *ArticleServiceGetCommentsLastRq) (*ArticleServiceGetCommentsLastRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsLast not implemented")
}
func (*UnimplementedArticleServiceServer) GetBook(ctx context.Context, req *ArticleServiceGetBookRq) (*ArticleServiceGetBookRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedArticleServiceServer) Update(ctx context.Context, req *ArticleServiceUpdateRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedArticleServiceServer) Delete(ctx context.Context, req *ArticleServiceDeleteRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedArticleServiceServer) Active(ctx context.Context, req *ArticleServiceActiveRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Active not implemented")
}
func (*UnimplementedArticleServiceServer) AddView(ctx context.Context, req *ArticleServiceViewRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddView not implemented")
}
func (*UnimplementedArticleServiceServer) TogglePublic(ctx context.Context, req *ArticleServicePublicRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TogglePublic not implemented")
}
func (*UnimplementedArticleServiceServer) Create(ctx context.Context, req *ArticleServiceCreateRq) (*ArticleServiceRsBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterArticleServiceServer(s *grpc.Server, srv ArticleServiceServer) {
	s.RegisterService(&_ArticleService_serviceDesc, srv)
}

func _ArticleService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetAllUsersRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetAllUsers(ctx, req.(*ArticleServiceGetAllUsersRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetAllRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetAll(ctx, req.(*ArticleServiceGetAllRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetPopular_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetPopularRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetPopular(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetPopular",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetPopular(ctx, req.(*ArticleServiceGetPopularRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).Get(ctx, req.(*ArticleServiceGetRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetCommentsRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetComments(ctx, req.(*ArticleServiceGetCommentsRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetCommentsLast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetCommentsLastRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetCommentsLast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetCommentsLast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetCommentsLast(ctx, req.(*ArticleServiceGetCommentsLastRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceGetBookRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetBook(ctx, req.(*ArticleServiceGetBookRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceUpdateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).Update(ctx, req.(*ArticleServiceUpdateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceDeleteRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).Delete(ctx, req.(*ArticleServiceDeleteRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_Active_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceActiveRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).Active(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/Active",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).Active(ctx, req.(*ArticleServiceActiveRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_AddView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceViewRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).AddView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/AddView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).AddView(ctx, req.(*ArticleServiceViewRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_TogglePublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServicePublicRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).TogglePublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/TogglePublic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).TogglePublic(ctx, req.(*ArticleServicePublicRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleServiceCreateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).Create(ctx, req.(*ArticleServiceCreateRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUsers",
			Handler:    _ArticleService_GetAllUsers_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ArticleService_GetAll_Handler,
		},
		{
			MethodName: "GetPopular",
			Handler:    _ArticleService_GetPopular_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ArticleService_Get_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _ArticleService_GetComments_Handler,
		},
		{
			MethodName: "GetCommentsLast",
			Handler:    _ArticleService_GetCommentsLast_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _ArticleService_GetBook_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ArticleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ArticleService_Delete_Handler,
		},
		{
			MethodName: "Active",
			Handler:    _ArticleService_Active_Handler,
		},
		{
			MethodName: "AddView",
			Handler:    _ArticleService_AddView_Handler,
		},
		{
			MethodName: "TogglePublic",
			Handler:    _ArticleService_TogglePublic_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ArticleService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/articleService.proto",
}
